title: Rocket
hero_image: images/banner.png
description: Create a model of a rocket using Blender
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: "space"
technologies: ""
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Base of the rocket
  - title: Body of the rocket
  - title: Nose cone
  - title: Colour the rocket
  - title: Add stripes
  - title: Red nose
